defaults:
  - defaults
  - motion_loader: bobsl_lmdb
  - text_encoder: clip
  - mdm
  - _self_

run_dir: models/mdm_bobsl3dt_phonology_hms
tmr_run_dir: models/tmr_bobsl3dt

dataset: bobsl3dt_test_manually_cleaned_phon_ms
tmr_dataset: ${dataset}

batch_size: 512
split: test_unseen
guidance: 15

ckpt: last
tmr_ckpt: last
device: cuda

render: True
render_max: 10
overwrite_rendering: False
with_mano: False
motion_test_gt_folder: bobsl3dt_test_manually_cleaned_phon_ms

seed: null

fixed_length: null

save_metrics: True
